### PR TITLE
Actions icons for clementine

### PR DESCRIPTION
**Pull request by varlesh**
Before:

After:

### CODE REVIEW

**Comment by varlesh** [comment]
Also i create applications-internet icon. But this icon used on Menu application. Maybe on Mate DE not good looking, but good looking on clementine.
applications-internet

**Comment by varlesh** [comment]
Change symlink "search" icon for best looking also ))

**Comment by JosephMcc** [comment]
Not a fan of changing the symlink for the search icon. This leaves you in the situation where it looks like one icon at one size and another at other sizes. I'm not sure where else it is used but it causes issues. Say for example you have an icon on the Mate panel that uses the "search" icon. If you resize the panel it can make the icon switch back and forth between the different sizes.

A lot of this was removed from the theme awhile back and I would rather not start seeing it put back.

**Comment by varlesh** [comment]
@JosephMcc Maybe cahnge all symlinks for "search" icon?

**Comment by JosephMcc** [comment]
@varlesh I'm not sure that's a good solution. I'm not sure where else that icon gets used. In a lot of cases those dark icons we use in the theme don't work well. That's the entire reason why we have to keep the Mint-X-Dark theme around.

I know you're trying to make clementine look nicer but that sort of change is likely to break in other situations and I'm not sure it's worth it for one app.

**Comment by varlesh** [comment]
@JosephMcc Why? Where new "search" icon not good looking? Mostly all actions icons as monochrome style. Also, I can add dark version, if you needed.

**Comment by varlesh** [comment]
Original Mint GTK Theme have light version and black icons best looking on grey, than white on grey

**Comment by varlesh** [comment]
You agree that this icon merges color - white & grey?
It's realy not good looking on any application.

**Comment by Yanpas** [comment]
I guess at least adding new icons is good solution anyway. And replacing current icons/symlinks is controversial. 
IMHO new PR without deletions and modifications will get green light

**Comment by varlesh** [comment]
@Yanpas Ах какая шальная аватарка у вас, улыбнуло ))
Вы используете Mate? Случаем не встречали где-либо эту иконку "search"?
Ведь реально меняется только символьная ссылка по сути, а внешний вид куда приятней получается. Тем более, заметьте что помимо слияние белого и серого цветов, что плохо для восприятия, еще сам иконка содержит какие-то черные две точки внизу.

**Comment by Yanpas** [comment]
@varlesh Нет, я использую XFCE :) Для порядочности перейду на английский. `(No I use XFCE :) For decency I will switch back to English.)`

I haven't met this icon anywhere else, may be it was just inherited from gnome theme. I guess it means another kind of search: search in the exact list of smth or  in a document. So I think it's good idea to draw in Inkscape some lines on the background or even monochrome text document. What do you think, @JosephMcc ?

PS: I'm not form Mint theme stuff and I do not manage PRs, it's just personal opinion.

**Comment by Yanpas** [comment]
@varlesh Magick! I've just discovered where this icon is used. It is icon of gnome-system-log app. So it's Clementine devs' problem, they are using wrong icon

**Comment by varlesh** [comment]
@Yanpas No, gnome-system-log use "logview" icon:
http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/trusty/gnome-system-log/trusty/view/head:/data/gnome-system-log.desktop.in.in
And symlink "logview" to "logviewer":
https://github.com/linuxmint/mint-x-icons/blob/master/usr/share/icons/Mint-X/apps/16/logview.png

**Comment by varlesh** [comment]
If realy new "search" icon not good looking on any aplication or spoils style? Please show me where this icon not combined.
Yes, "applications-internet" used on Menu categories and i not change this icon, because icon already exist and spoils style on Menu. 
But "search" -  this is just a symbolic link. I think "search" icon used only as action and monochrome style better variant for this.
Sorry, i must fix symlink 16px - "search" as "stock_search" )

**Comment by JosephMcc** [comment]
In the end you may be correct that changing the link won't have any negative side effects. I don't know where else that icon is used but since it was added to the theme at some point that means it is used somewhere or it wouldn't have been added.

Just a couple other notes. When adding icons, in most cases you want to add the icons in all the available sizes. With HiDpi it's almost a requirement for them to work correctly. Since the icons you're adding seem to be specific to Clementine, it may not matter in this case. It's also a good idea a lot of the time to squash your commits down into a single commit.

**Comment by varlesh** [comment]
@JosephMcc Ok. I later add other icons and symlink for HDPi.
Close this commit now and open later new one single.
But, i can change "search" symlink or no?

**Pull request closed without merging**
