### PR TITLE
Added icons for a number of phones

### PR DESCRIPTION
**Pull request by W-Floyd**
Motorola Moto G 2 model number could alternatively be "XT1068"

### CODE REVIEW

**Comment by RollaTroll** [comment]
I am unsure what the naming standards are when specifying colours.

**Comment by muzena** [comment]
@W-Floyd 
I don't understand for what is this mobile icons, or when/where is showibg these mobile icons?

**Comment by W-Floyd** [comment]
These are icons for specific phone models.

They should be used like this:
2016-05-07-190307_440x317_scrot

Rather than the default:
2016-05-07-190429_429x277_scrot

I have not yet found a way to assign them to a device in a way that will appear across the whole system.
However, I do think someone may find them useful, and if icons are created, there is more incentive to implement a feature to use them appropriatelky

If this is not a good place to submit them, then direct me to the appropriate location.

**Comment by muzena** [comment]
@W-Floyd 
Aha, I didn't never noticed this in My computer icon when i connected my phone.

**Comment by muzena** [comment]
@W-Floyd 
Can you make icons for these phones
http://www.thlmobilestore.com/thl-5000-mtk6592-octa-core-android-4-2-2gb-32gb-smartphone-5-0-inch.html
https://en.wikipedia.org/wiki/LG_Optimus_2X

**Comment by W-Floyd** [comment]
@muzena Sure, I'll have a look at it!

**Pull request merged**
