### PR TITLE
Added icons for multiple phones

### PR DESCRIPTION
**Pull request by W-Floyd**

### CODE REVIEW

**Comment by W-Floyd** [comment]
@muzena

As per your request, here you go.

**Comment by muzena** [comment]
@W-Floyd 
Thanks a lot.
If it not so hard can you add these few phones that i have:
http://www.samsung.com/hr/consumer/mobile-devices/smartphones/galaxy-s/GT-I9305MBDVIP
http://www.samsung.com/hr/consumer/mobile-devices/smartphones/galaxy-s/GT-I8190RWACRO
http://www.sonymobile.com/global-en/products/phones/xperia-m2/specifications/
http://www.phonearena.com/phones/Sony-Ericsson-Xperia-X8_id4734

**Comment by W-Floyd** [comment]
I'll see what I can do.

**Comment by JosephMcc** [comment]
Sorry if I'm a bit confused. But does something actually make use of the different phone icons? If so where do they show up?

**Comment by W-Floyd** [comment]
@JosephMcc 
(From a previous comment to muzena)
These are icons for specific phone models.

They should be used like this:
2016-05-07-190307_440x317_scrot

Rather than the default:
2016-05-07-190429_429x277_scrot

I have not yet found a way to assign them to a device in a way that will appear across the _whole_ system.
However, I do think someone may find them useful, and if icons are created, there is more incentive to implement a feature to use them appropriately

If this is not a good place to submit them, then direct me to the appropriate location.

**Comment by JosephMcc** [comment]
Well that pretty much answered my question. They actually aren't used anywhere.

**Comment by clefebvre** [comment]
Ah... I assumed these were being used by nemo, depending on the phone model being plugged. If that's not the case, there is no need for such icons. Nemo would need to implement the necessary feature first.

**Comment by W-Floyd** [comment]
Fair enough. Should the Motorola Droid icon be removed also then?

**Pull request closed without merging**
