### PR TITLE
steam tray png

### PR DESCRIPTION
**Pull request by Yanpas**
#91 issue

### CODE REVIEW

**Comment by darealshinji** [comment]
bildschirmfoto
You need to add icons in lower resolutions too, otherwise it looks kinda broken in MATE (though that's probably a bug in MATE).

steam_tray_mono steam_tray_mono steam_tray_mono steam_tray_mono

**Comment by Yanpas** [comment]
Added icons. I'm writing this comment cause think that you might won't be notified about my 2nd commit :) Have you recieved notification abou commit 8a73c6a?)

**Comment by darealshinji** [comment]
No, I've only been notified about your comment.

**Comment by Yanpas** [comment]
Don't you think that lines are too thin for Mint icons? NM-applet and sound icon has thicker lines. This is definetelly better then it was before, but I don't know how to make in more "Minty"

**Comment by clefebvre** [comment]
Hi,

It looks nice in a light panel but not in a dark panel. The light line contour around the circle should be removed.

Also, I noticed the radiotray status icon looked good in both light and dark panel. Maybe we could do like them and simply use the same status icon as Steam but change its color to #7e7e7e.

**Comment by darealshinji** [comment]
@clefebvre Will this do it?
``` SVG
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0) -->
<!-- Source: http://boneyardbrew.deviantart.com/art/Modern-Steam-Icon-421263397 -->

<svg version="1.2" baseProfile="tiny" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px"
	 y="0px" width="255.835px" height="256.162px" viewBox="0 0 255.835 256.162" xml:space="preserve">
<g id="BG" style="fill:#7e7e7e">
	<path fill-rule="evenodd" d="M128.001,0.167c70.692,0,128,57.308,128,128s-57.308,128-128,128s-128-57.308-128-128
		S57.309,0.167,128.001,0.167z"/>
</g>
<g id="Logo">
	<g>
		<path fill="white" d="M171.056,69.985c-13.496,0-24.437,10.94-24.437,24.436c0,13.496,10.94,24.437,24.437,24.437
			s24.437-10.94,24.437-24.437C195.492,80.925,184.552,69.985,171.056,69.985z M171.056,46.712
			c-26.323,0-47.664,21.317-47.708,47.629l-31.225,45.796c-1.587-0.214-3.204-0.334-4.85-0.334c-7.649,0-14.737,2.388-20.573,6.448
			L0.301,119.468c-0.193,2.875-0.3,5.774-0.3,8.699c0,12.187,1.704,23.975,4.885,35.141l46.958,19.333
			c3.167,16.688,17.82,29.309,35.43,29.309c19.923,0,36.073-16.15,36.073-36.073c0-0.88-0.042-1.749-0.104-2.613l47.739-31.134
			c0.025,0,0.05,0.002,0.075,0.002c26.349,0,47.709-21.36,47.709-47.709S197.404,46.712,171.056,46.712z M87.273,202.639
			c-10.712,0-19.95-6.296-24.227-15.387l15.859,6.529c0.55,0.258,1.113,0.488,1.689,0.695l0.569,0.234l0.009-0.022
			c1.922,0.623,3.97,0.969,6.1,0.969c10.925,0,19.782-8.856,19.782-19.782c0-7.648-4.349-14.271-10.703-17.563l0.036-0.086
			l-1.31-0.528c-0.108-0.046-0.218-0.087-0.327-0.132l-16.81-6.78c2.906-1.081,6.048-1.675,9.331-1.675
			c14.781,0,26.764,11.982,26.764,26.764S102.055,202.639,87.273,202.639z M171.056,128.167c-18.638,0-33.746-15.108-33.746-33.746
			s15.108-33.745,33.746-33.745c18.637,0,33.745,15.108,33.745,33.745S189.692,128.167,171.056,128.167z"/>
	</g>
</g>
</svg>
```

**Comment by Yanpas** [comment]
I agree with clefebvre, radioactive icon looks better. SVG icons are eclectic. Proposed icon upper is too light. Guess that dark color should be equal the color of tray icons (sound etc...) and the light color should be equal to panel color or color of cinnamon applets

**Comment by clefebvre** [comment]
I think so. I'll try to get Joseph here, he's got ideas for it as well.

**Comment by JosephMcc** [comment]
I'm not a big fan of including the bg on the icon. On my Cinnamon desktop right now I have dropbox, hexchat and mint update icons in the systray and none of them include a bg. I took a shot at creating a 24px steam tray icon that would look reasonable on both light and dark panels:

steam-tray

I'll be the first to admit I'm not the most spectacular inkscape artist but I think something along these lines would be better.

**Pull request closed without merging**
