### PR TITLE
HexChat icons (symlinks to xchat icons)

### PR DESCRIPTION
**Pull request by darealshinji**

### CODE REVIEW

**Comment by clefebvre** [comment]
That won't work afaik.

**Comment by clefebvre** [comment]
Hexchat has an hexagon.

**Comment by darealshinji** [comment]
The current xchat icon looks more like a general chat program icon to me, so I thought it could be used for Hexchat too.

**Comment by darealshinji** [comment]
I just saw that the MATE guys did the same for mate-icon-theme-faenza.

**Comment by clefebvre** [comment]
There's a problem with the systray icon not matching the app icon then.

**Comment by JosephMcc** [comment]
XChat and Hexchat are separate apps and have different logos. They should be different imo.

**Comment by darealshinji** [comment]
@JosephMcc Yeah, makes sense.

What about this draft?
hexchat
[hexchat.svg](https://gist.github.com/darealshinji/0d0f56a8bcb43115c39d)

**Comment by JosephMcc** [comment]
@darealshinji 

The orange on green is a bit much for my personal tastes :). I haven't tried but if we add a hexchat icon to the theme does it affect the icon shown in the panel system tray? If it does I would prefer keeping the current one without a background.

**Comment by clefebvre** [comment]
If you change the icon it won't affect the systray afaik. For this reason it should be similar.. you can add a background to it, but respect the logo inside it.

Green is way too much, I agree :)

**Comment by darealshinji** [comment]
A simple bright background then? Or any suggestions for a color that fits well with the orange icon?
hexchat
[hexchat.svg](https://gist.github.com/darealshinji/0d0f56a8bcb43115c39d)

**Comment by JosephMcc** [comment]
Maybe a dark background.
hexchat

**Comment by clefebvre** [comment]
Yes.

**Comment by GLolol** [comment]
I like the white one: the black outline of the logo contrasts better with a brighter background.

**Comment by darealshinji** [comment]
Since this issue is closed, will one of the drafts from this discussion be added?

**Pull request closed without merging**
