### PR TITLE
Mint-X GIMP shows Wilber instead of color stains

### PR DESCRIPTION
**Pull request by theSeppi**

### CODE REVIEW

**Comment by GLolol** [comment]
That looks nice! Is the 48 icon supposed to be 49x48?

**Comment by theSeppi** [comment]
Nope, thank you. I fixed it. Maybe some floating precision issue when exporting from Inkscape...

**Comment by clefebvre** [comment]
Would it look better without the hole?

**Comment by theSeppi** [comment]
Personally, I don't think so. Plus, this might require some hard work if it's important to keep it as an SVG, as the wood pattern seems to stop around the hole, but I could trial-and-error edit the SVG as text and maybe it'll work...

**Comment by JosephMcc** [comment]
Without the hole for sure.

**Comment by theSeppi** [comment]
@clefebvre Would you like to pose an opinion on this, too?

**Comment by GLolol** [comment]
I like it better without the hole (the hole just seems awkwardly placed and a bit of it is covered by the brush anyways).

**Comment by theSeppi** [comment]
I now removed the hole as I noticed that it looked rather strange in the application menu...

**Pull request merged**
